# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
steps:
- task: Azure Extension for execution of Test under TTT@0
  inputs:
    HCIConnection: 'CW13.bmc.com'
    HCIConnectionPort: '16196'
    UserID: 'pinawm1'
    Password: 'Moab22'
    PassTicket: 'passticket'
    TestLocationPath: 'C:\AzureTestCase\Tests5\Scenarios'
    CLIInstallationPath: 'C:\Topaz\WorkbenchCLI\'
    Configuration: 'C:\AzureTestCase\TotalTestConfiguration'

trigger:
- master

pool:
  name: default


